### ISSUE TITLE
Second extruder tempreture reporting code is missing for M105 command

### ISSUE THREAD

**Issue by guysoft** [InventAPart/RigidBot-Firmware#1]
Hey,
The second extruder does not report temperature when sent an M105 command.
This is because there is a block of code that is missing!
take a look here: https://github.com/MarlinFirmware/Marlin/blob/Development/Marlin/Marlin_main.cpp#L2451
and compare that with: https://github.com/InventAPart/RigidBot-Firmware/blob/e02d6db60425afdc22ad49add5266ca99b888977/Marlin/Marlin_main.cpp#L1116
that whole for block is missing!

The result is that software like Repetier and OctoPrint don't see that extruder as on.

**Comment by joshvillbrandt** [comment]
Hey @guysoft, this repository is currently unmaintained. I attempt to get InventAPart to manage their firmware development through GitHub to no avail. I merged your pull request, but we should probably reconcile this repo with InventAPart at some point.

If you're interested in keeping this alive, I'll happily make you a maintainer of this InventAPart GitHub group.

https://plus.google.com/communities/117996416225488251038

**Comment by guysoft** [comment]
Hey @joshvillbrandt ,
With a bug like that I wonder if anyone is actually using this code. It would seem putting effort in the community version would be a much smarter move.

Did you try phoning Michael?
